# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luka/ClionProjects/sbt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luka/ClionProjects/sbt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luka/ClionProjects/sbt/CMakeFiles /home/luka/ClionProjects/sbt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luka/ClionProjects/sbt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sbt

# Build rule for target.
sbt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sbt
.PHONY : sbt

# fast build rule for target.
sbt/fast:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/build
.PHONY : sbt/fast

bloom/AstralBloomFilter.o: bloom/AstralBloomFilter.cpp.o

.PHONY : bloom/AstralBloomFilter.o

# target to build an object file
bloom/AstralBloomFilter.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/AstralBloomFilter.cpp.o
.PHONY : bloom/AstralBloomFilter.cpp.o

bloom/AstralBloomFilter.i: bloom/AstralBloomFilter.cpp.i

.PHONY : bloom/AstralBloomFilter.i

# target to preprocess a source file
bloom/AstralBloomFilter.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/AstralBloomFilter.cpp.i
.PHONY : bloom/AstralBloomFilter.cpp.i

bloom/AstralBloomFilter.s: bloom/AstralBloomFilter.cpp.s

.PHONY : bloom/AstralBloomFilter.s

# target to generate assembly for a file
bloom/AstralBloomFilter.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/AstralBloomFilter.cpp.s
.PHONY : bloom/AstralBloomFilter.cpp.s

bloom/BloomFilter.o: bloom/BloomFilter.cpp.o

.PHONY : bloom/BloomFilter.o

# target to build an object file
bloom/BloomFilter.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/BloomFilter.cpp.o
.PHONY : bloom/BloomFilter.cpp.o

bloom/BloomFilter.i: bloom/BloomFilter.cpp.i

.PHONY : bloom/BloomFilter.i

# target to preprocess a source file
bloom/BloomFilter.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/BloomFilter.cpp.i
.PHONY : bloom/BloomFilter.cpp.i

bloom/BloomFilter.s: bloom/BloomFilter.cpp.s

.PHONY : bloom/BloomFilter.s

# target to generate assembly for a file
bloom/BloomFilter.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/BloomFilter.cpp.s
.PHONY : bloom/BloomFilter.cpp.s

bloom/SimpleBloomFilter.o: bloom/SimpleBloomFilter.cpp.o

.PHONY : bloom/SimpleBloomFilter.o

# target to build an object file
bloom/SimpleBloomFilter.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/SimpleBloomFilter.cpp.o
.PHONY : bloom/SimpleBloomFilter.cpp.o

bloom/SimpleBloomFilter.i: bloom/SimpleBloomFilter.cpp.i

.PHONY : bloom/SimpleBloomFilter.i

# target to preprocess a source file
bloom/SimpleBloomFilter.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/SimpleBloomFilter.cpp.i
.PHONY : bloom/SimpleBloomFilter.cpp.i

bloom/SimpleBloomFilter.s: bloom/SimpleBloomFilter.cpp.s

.PHONY : bloom/SimpleBloomFilter.s

# target to generate assembly for a file
bloom/SimpleBloomFilter.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/SimpleBloomFilter.cpp.s
.PHONY : bloom/SimpleBloomFilter.cpp.s

bloom/factory/BloomFilterFactory.o: bloom/factory/BloomFilterFactory.cpp.o

.PHONY : bloom/factory/BloomFilterFactory.o

# target to build an object file
bloom/factory/BloomFilterFactory.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/factory/BloomFilterFactory.cpp.o
.PHONY : bloom/factory/BloomFilterFactory.cpp.o

bloom/factory/BloomFilterFactory.i: bloom/factory/BloomFilterFactory.cpp.i

.PHONY : bloom/factory/BloomFilterFactory.i

# target to preprocess a source file
bloom/factory/BloomFilterFactory.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/factory/BloomFilterFactory.cpp.i
.PHONY : bloom/factory/BloomFilterFactory.cpp.i

bloom/factory/BloomFilterFactory.s: bloom/factory/BloomFilterFactory.cpp.s

.PHONY : bloom/factory/BloomFilterFactory.s

# target to generate assembly for a file
bloom/factory/BloomFilterFactory.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/factory/BloomFilterFactory.cpp.s
.PHONY : bloom/factory/BloomFilterFactory.cpp.s

bloom/hash/AstralHashFn.o: bloom/hash/AstralHashFn.cpp.o

.PHONY : bloom/hash/AstralHashFn.o

# target to build an object file
bloom/hash/AstralHashFn.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/AstralHashFn.cpp.o
.PHONY : bloom/hash/AstralHashFn.cpp.o

bloom/hash/AstralHashFn.i: bloom/hash/AstralHashFn.cpp.i

.PHONY : bloom/hash/AstralHashFn.i

# target to preprocess a source file
bloom/hash/AstralHashFn.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/AstralHashFn.cpp.i
.PHONY : bloom/hash/AstralHashFn.cpp.i

bloom/hash/AstralHashFn.s: bloom/hash/AstralHashFn.cpp.s

.PHONY : bloom/hash/AstralHashFn.s

# target to generate assembly for a file
bloom/hash/AstralHashFn.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/AstralHashFn.cpp.s
.PHONY : bloom/hash/AstralHashFn.cpp.s

bloom/hash/HashFn.o: bloom/hash/HashFn.cpp.o

.PHONY : bloom/hash/HashFn.o

# target to build an object file
bloom/hash/HashFn.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/HashFn.cpp.o
.PHONY : bloom/hash/HashFn.cpp.o

bloom/hash/HashFn.i: bloom/hash/HashFn.cpp.i

.PHONY : bloom/hash/HashFn.i

# target to preprocess a source file
bloom/hash/HashFn.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/HashFn.cpp.i
.PHONY : bloom/hash/HashFn.cpp.i

bloom/hash/HashFn.s: bloom/hash/HashFn.cpp.s

.PHONY : bloom/hash/HashFn.s

# target to generate assembly for a file
bloom/hash/HashFn.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/HashFn.cpp.s
.PHONY : bloom/hash/HashFn.cpp.s

bloom/hash/HashFnSingleton.o: bloom/hash/HashFnSingleton.cpp.o

.PHONY : bloom/hash/HashFnSingleton.o

# target to build an object file
bloom/hash/HashFnSingleton.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/HashFnSingleton.cpp.o
.PHONY : bloom/hash/HashFnSingleton.cpp.o

bloom/hash/HashFnSingleton.i: bloom/hash/HashFnSingleton.cpp.i

.PHONY : bloom/hash/HashFnSingleton.i

# target to preprocess a source file
bloom/hash/HashFnSingleton.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/HashFnSingleton.cpp.i
.PHONY : bloom/hash/HashFnSingleton.cpp.i

bloom/hash/HashFnSingleton.s: bloom/hash/HashFnSingleton.cpp.s

.PHONY : bloom/hash/HashFnSingleton.s

# target to generate assembly for a file
bloom/hash/HashFnSingleton.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/HashFnSingleton.cpp.s
.PHONY : bloom/hash/HashFnSingleton.cpp.s

bloom/hash/SimpleHashFn.o: bloom/hash/SimpleHashFn.cpp.o

.PHONY : bloom/hash/SimpleHashFn.o

# target to build an object file
bloom/hash/SimpleHashFn.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/SimpleHashFn.cpp.o
.PHONY : bloom/hash/SimpleHashFn.cpp.o

bloom/hash/SimpleHashFn.i: bloom/hash/SimpleHashFn.cpp.i

.PHONY : bloom/hash/SimpleHashFn.i

# target to preprocess a source file
bloom/hash/SimpleHashFn.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/SimpleHashFn.cpp.i
.PHONY : bloom/hash/SimpleHashFn.cpp.i

bloom/hash/SimpleHashFn.s: bloom/hash/SimpleHashFn.cpp.s

.PHONY : bloom/hash/SimpleHashFn.s

# target to generate assembly for a file
bloom/hash/SimpleHashFn.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/bloom/hash/SimpleHashFn.cpp.s
.PHONY : bloom/hash/SimpleHashFn.cpp.s

dna/AstralSequence.o: dna/AstralSequence.cpp.o

.PHONY : dna/AstralSequence.o

# target to build an object file
dna/AstralSequence.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/AstralSequence.cpp.o
.PHONY : dna/AstralSequence.cpp.o

dna/AstralSequence.i: dna/AstralSequence.cpp.i

.PHONY : dna/AstralSequence.i

# target to preprocess a source file
dna/AstralSequence.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/AstralSequence.cpp.i
.PHONY : dna/AstralSequence.cpp.i

dna/AstralSequence.s: dna/AstralSequence.cpp.s

.PHONY : dna/AstralSequence.s

# target to generate assembly for a file
dna/AstralSequence.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/AstralSequence.cpp.s
.PHONY : dna/AstralSequence.cpp.s

dna/Kmer.o: dna/Kmer.cpp.o

.PHONY : dna/Kmer.o

# target to build an object file
dna/Kmer.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/Kmer.cpp.o
.PHONY : dna/Kmer.cpp.o

dna/Kmer.i: dna/Kmer.cpp.i

.PHONY : dna/Kmer.i

# target to preprocess a source file
dna/Kmer.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/Kmer.cpp.i
.PHONY : dna/Kmer.cpp.i

dna/Kmer.s: dna/Kmer.cpp.s

.PHONY : dna/Kmer.s

# target to generate assembly for a file
dna/Kmer.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/Kmer.cpp.s
.PHONY : dna/Kmer.cpp.s

dna/Sequence.o: dna/Sequence.cpp.o

.PHONY : dna/Sequence.o

# target to build an object file
dna/Sequence.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/Sequence.cpp.o
.PHONY : dna/Sequence.cpp.o

dna/Sequence.i: dna/Sequence.cpp.i

.PHONY : dna/Sequence.i

# target to preprocess a source file
dna/Sequence.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/Sequence.cpp.i
.PHONY : dna/Sequence.cpp.i

dna/Sequence.s: dna/Sequence.cpp.s

.PHONY : dna/Sequence.s

# target to generate assembly for a file
dna/Sequence.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/Sequence.cpp.s
.PHONY : dna/Sequence.cpp.s

dna/SimpleKmer.o: dna/SimpleKmer.cpp.o

.PHONY : dna/SimpleKmer.o

# target to build an object file
dna/SimpleKmer.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/SimpleKmer.cpp.o
.PHONY : dna/SimpleKmer.cpp.o

dna/SimpleKmer.i: dna/SimpleKmer.cpp.i

.PHONY : dna/SimpleKmer.i

# target to preprocess a source file
dna/SimpleKmer.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/SimpleKmer.cpp.i
.PHONY : dna/SimpleKmer.cpp.i

dna/SimpleKmer.s: dna/SimpleKmer.cpp.s

.PHONY : dna/SimpleKmer.s

# target to generate assembly for a file
dna/SimpleKmer.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/SimpleKmer.cpp.s
.PHONY : dna/SimpleKmer.cpp.s

dna/SimpleSequence.o: dna/SimpleSequence.cpp.o

.PHONY : dna/SimpleSequence.o

# target to build an object file
dna/SimpleSequence.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/SimpleSequence.cpp.o
.PHONY : dna/SimpleSequence.cpp.o

dna/SimpleSequence.i: dna/SimpleSequence.cpp.i

.PHONY : dna/SimpleSequence.i

# target to preprocess a source file
dna/SimpleSequence.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/SimpleSequence.cpp.i
.PHONY : dna/SimpleSequence.cpp.i

dna/SimpleSequence.s: dna/SimpleSequence.cpp.s

.PHONY : dna/SimpleSequence.s

# target to generate assembly for a file
dna/SimpleSequence.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/dna/SimpleSequence.cpp.s
.PHONY : dna/SimpleSequence.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/main.cpp.s
.PHONY : main.cpp.s

tree/Node.o: tree/Node.cpp.o

.PHONY : tree/Node.o

# target to build an object file
tree/Node.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/Node.cpp.o
.PHONY : tree/Node.cpp.o

tree/Node.i: tree/Node.cpp.i

.PHONY : tree/Node.i

# target to preprocess a source file
tree/Node.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/Node.cpp.i
.PHONY : tree/Node.cpp.i

tree/Node.s: tree/Node.cpp.s

.PHONY : tree/Node.s

# target to generate assembly for a file
tree/Node.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/Node.cpp.s
.PHONY : tree/Node.cpp.s

tree/Tree.o: tree/Tree.cpp.o

.PHONY : tree/Tree.o

# target to build an object file
tree/Tree.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/Tree.cpp.o
.PHONY : tree/Tree.cpp.o

tree/Tree.i: tree/Tree.cpp.i

.PHONY : tree/Tree.i

# target to preprocess a source file
tree/Tree.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/Tree.cpp.i
.PHONY : tree/Tree.cpp.i

tree/Tree.s: tree/Tree.cpp.s

.PHONY : tree/Tree.s

# target to generate assembly for a file
tree/Tree.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/Tree.cpp.s
.PHONY : tree/Tree.cpp.s

tree/query/DepthQueryProcessor.o: tree/query/DepthQueryProcessor.cpp.o

.PHONY : tree/query/DepthQueryProcessor.o

# target to build an object file
tree/query/DepthQueryProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/DepthQueryProcessor.cpp.o
.PHONY : tree/query/DepthQueryProcessor.cpp.o

tree/query/DepthQueryProcessor.i: tree/query/DepthQueryProcessor.cpp.i

.PHONY : tree/query/DepthQueryProcessor.i

# target to preprocess a source file
tree/query/DepthQueryProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/DepthQueryProcessor.cpp.i
.PHONY : tree/query/DepthQueryProcessor.cpp.i

tree/query/DepthQueryProcessor.s: tree/query/DepthQueryProcessor.cpp.s

.PHONY : tree/query/DepthQueryProcessor.s

# target to generate assembly for a file
tree/query/DepthQueryProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/DepthQueryProcessor.cpp.s
.PHONY : tree/query/DepthQueryProcessor.cpp.s

tree/query/DepthQueryUnit.o: tree/query/DepthQueryUnit.cpp.o

.PHONY : tree/query/DepthQueryUnit.o

# target to build an object file
tree/query/DepthQueryUnit.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/DepthQueryUnit.cpp.o
.PHONY : tree/query/DepthQueryUnit.cpp.o

tree/query/DepthQueryUnit.i: tree/query/DepthQueryUnit.cpp.i

.PHONY : tree/query/DepthQueryUnit.i

# target to preprocess a source file
tree/query/DepthQueryUnit.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/DepthQueryUnit.cpp.i
.PHONY : tree/query/DepthQueryUnit.cpp.i

tree/query/DepthQueryUnit.s: tree/query/DepthQueryUnit.cpp.s

.PHONY : tree/query/DepthQueryUnit.s

# target to generate assembly for a file
tree/query/DepthQueryUnit.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/DepthQueryUnit.cpp.s
.PHONY : tree/query/DepthQueryUnit.cpp.s

tree/query/QueryProcessor.o: tree/query/QueryProcessor.cpp.o

.PHONY : tree/query/QueryProcessor.o

# target to build an object file
tree/query/QueryProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/QueryProcessor.cpp.o
.PHONY : tree/query/QueryProcessor.cpp.o

tree/query/QueryProcessor.i: tree/query/QueryProcessor.cpp.i

.PHONY : tree/query/QueryProcessor.i

# target to preprocess a source file
tree/query/QueryProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/QueryProcessor.cpp.i
.PHONY : tree/query/QueryProcessor.cpp.i

tree/query/QueryProcessor.s: tree/query/QueryProcessor.cpp.s

.PHONY : tree/query/QueryProcessor.s

# target to generate assembly for a file
tree/query/QueryProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/QueryProcessor.cpp.s
.PHONY : tree/query/QueryProcessor.cpp.s

tree/query/QueryUnit.o: tree/query/QueryUnit.cpp.o

.PHONY : tree/query/QueryUnit.o

# target to build an object file
tree/query/QueryUnit.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/QueryUnit.cpp.o
.PHONY : tree/query/QueryUnit.cpp.o

tree/query/QueryUnit.i: tree/query/QueryUnit.cpp.i

.PHONY : tree/query/QueryUnit.i

# target to preprocess a source file
tree/query/QueryUnit.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/QueryUnit.cpp.i
.PHONY : tree/query/QueryUnit.cpp.i

tree/query/QueryUnit.s: tree/query/QueryUnit.cpp.s

.PHONY : tree/query/QueryUnit.s

# target to generate assembly for a file
tree/query/QueryUnit.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/QueryUnit.cpp.s
.PHONY : tree/query/QueryUnit.cpp.s

tree/query/SequenceDepthQueryUnit.o: tree/query/SequenceDepthQueryUnit.cpp.o

.PHONY : tree/query/SequenceDepthQueryUnit.o

# target to build an object file
tree/query/SequenceDepthQueryUnit.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/SequenceDepthQueryUnit.cpp.o
.PHONY : tree/query/SequenceDepthQueryUnit.cpp.o

tree/query/SequenceDepthQueryUnit.i: tree/query/SequenceDepthQueryUnit.cpp.i

.PHONY : tree/query/SequenceDepthQueryUnit.i

# target to preprocess a source file
tree/query/SequenceDepthQueryUnit.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/SequenceDepthQueryUnit.cpp.i
.PHONY : tree/query/SequenceDepthQueryUnit.cpp.i

tree/query/SequenceDepthQueryUnit.s: tree/query/SequenceDepthQueryUnit.cpp.s

.PHONY : tree/query/SequenceDepthQueryUnit.s

# target to generate assembly for a file
tree/query/SequenceDepthQueryUnit.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/SequenceDepthQueryUnit.cpp.s
.PHONY : tree/query/SequenceDepthQueryUnit.cpp.s

tree/query/SimpleQueryProcessor.o: tree/query/SimpleQueryProcessor.cpp.o

.PHONY : tree/query/SimpleQueryProcessor.o

# target to build an object file
tree/query/SimpleQueryProcessor.cpp.o:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/SimpleQueryProcessor.cpp.o
.PHONY : tree/query/SimpleQueryProcessor.cpp.o

tree/query/SimpleQueryProcessor.i: tree/query/SimpleQueryProcessor.cpp.i

.PHONY : tree/query/SimpleQueryProcessor.i

# target to preprocess a source file
tree/query/SimpleQueryProcessor.cpp.i:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/SimpleQueryProcessor.cpp.i
.PHONY : tree/query/SimpleQueryProcessor.cpp.i

tree/query/SimpleQueryProcessor.s: tree/query/SimpleQueryProcessor.cpp.s

.PHONY : tree/query/SimpleQueryProcessor.s

# target to generate assembly for a file
tree/query/SimpleQueryProcessor.cpp.s:
	$(MAKE) -f CMakeFiles/sbt.dir/build.make CMakeFiles/sbt.dir/tree/query/SimpleQueryProcessor.cpp.s
.PHONY : tree/query/SimpleQueryProcessor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sbt"
	@echo "... bloom/AstralBloomFilter.o"
	@echo "... bloom/AstralBloomFilter.i"
	@echo "... bloom/AstralBloomFilter.s"
	@echo "... bloom/BloomFilter.o"
	@echo "... bloom/BloomFilter.i"
	@echo "... bloom/BloomFilter.s"
	@echo "... bloom/SimpleBloomFilter.o"
	@echo "... bloom/SimpleBloomFilter.i"
	@echo "... bloom/SimpleBloomFilter.s"
	@echo "... bloom/factory/BloomFilterFactory.o"
	@echo "... bloom/factory/BloomFilterFactory.i"
	@echo "... bloom/factory/BloomFilterFactory.s"
	@echo "... bloom/hash/AstralHashFn.o"
	@echo "... bloom/hash/AstralHashFn.i"
	@echo "... bloom/hash/AstralHashFn.s"
	@echo "... bloom/hash/HashFn.o"
	@echo "... bloom/hash/HashFn.i"
	@echo "... bloom/hash/HashFn.s"
	@echo "... bloom/hash/HashFnSingleton.o"
	@echo "... bloom/hash/HashFnSingleton.i"
	@echo "... bloom/hash/HashFnSingleton.s"
	@echo "... bloom/hash/SimpleHashFn.o"
	@echo "... bloom/hash/SimpleHashFn.i"
	@echo "... bloom/hash/SimpleHashFn.s"
	@echo "... dna/AstralSequence.o"
	@echo "... dna/AstralSequence.i"
	@echo "... dna/AstralSequence.s"
	@echo "... dna/Kmer.o"
	@echo "... dna/Kmer.i"
	@echo "... dna/Kmer.s"
	@echo "... dna/Sequence.o"
	@echo "... dna/Sequence.i"
	@echo "... dna/Sequence.s"
	@echo "... dna/SimpleKmer.o"
	@echo "... dna/SimpleKmer.i"
	@echo "... dna/SimpleKmer.s"
	@echo "... dna/SimpleSequence.o"
	@echo "... dna/SimpleSequence.i"
	@echo "... dna/SimpleSequence.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tree/Node.o"
	@echo "... tree/Node.i"
	@echo "... tree/Node.s"
	@echo "... tree/Tree.o"
	@echo "... tree/Tree.i"
	@echo "... tree/Tree.s"
	@echo "... tree/query/DepthQueryProcessor.o"
	@echo "... tree/query/DepthQueryProcessor.i"
	@echo "... tree/query/DepthQueryProcessor.s"
	@echo "... tree/query/DepthQueryUnit.o"
	@echo "... tree/query/DepthQueryUnit.i"
	@echo "... tree/query/DepthQueryUnit.s"
	@echo "... tree/query/QueryProcessor.o"
	@echo "... tree/query/QueryProcessor.i"
	@echo "... tree/query/QueryProcessor.s"
	@echo "... tree/query/QueryUnit.o"
	@echo "... tree/query/QueryUnit.i"
	@echo "... tree/query/QueryUnit.s"
	@echo "... tree/query/SequenceDepthQueryUnit.o"
	@echo "... tree/query/SequenceDepthQueryUnit.i"
	@echo "... tree/query/SequenceDepthQueryUnit.s"
	@echo "... tree/query/SimpleQueryProcessor.o"
	@echo "... tree/query/SimpleQueryProcessor.i"
	@echo "... tree/query/SimpleQueryProcessor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

